all: eigDoc

# main documentation for genEigs, Ogev
eigDoc:
	pdflatex eigDoc


notes:
	pdflatex notes

# EVE DOC
eve:
	pdflatex eve
	bibtex eve

# Ogev doc
# ogev:
# 	pdflatex ogev
# 	bibtex ogev








