%
%  Find eigenvalues of the incompressible elasticity equations
%    Use matrices A and B from files generated by genEigs.bC 
%

% Set defaults for plotting 
fontSize=16; lineWidth=2; markerSize=8; 
set(0,'DefaultLineMarkerSize',markerSize);
set(0,'DefaultLineLineWidth',lineWidth);
set(0,'DefaultAxesFontSize',fontSize);
set(0,'DefaultLegendFontSize',fontSize);

rainbow;

eigMatA
[m,n]=size(A);

Af=full(A);
rankA = rank(Af);
fprintf('A = %d x %d, Rank(A)=%d\n',m,n,rankA);

eigMatB

[V,D] = eigs(B,A);

lam = 1./diag(D)
numEigs = length(lam);
% lam = 1./d


%   +--+--A--+--+-- ... --B--+--+ 
%  -2 -1  0  1  2         nx 
%         iax             ibx 
% 
nxd = sqrt(m);  % = nx +2*numGost
nyd = nxd;  
numGhost=2;
nx = nxd-2*numGhost-1;
ny = nx; 
iax = numGhost+1; ibx = iax+nx; 
iay = numGhost+1; iby = iay+ny; 




x = zeros(nxd,nyd);
y = zeros(nxd,nyd);
dx = 1/nx; dy=1/ny;

for i=1:nxd 
  for j=1:nyd
    x(i,j) = (i-iax)*dx;
    y(i,j) = (j-iay)*dy;
  end
end 

I1=iax:ibx; I2=iay:iby; % no ghost t

for eigc=1:numEigs
  psi = V(:,eigc);
  psi = reshape(psi,[nxd,nyd]);
  
  
  figure(1);
  colormap(rainbowMap);
  surf(x,y,psi);
  title('\psi with ghost');
  % shading interp;
  
  figure(2)
  surf(x(I1,I2),y(I1,I2),psi(I1,I2));
  title(sprintf('\\psi eig=%d \\lambda=%g',eigc,lam(eigc))); 
  xlabel('x'); ylabel('y'); 

  pause
end




